# Generated by Django 4.1.7 on 2023-06-21 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_davomat_date_alter_student_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 17, 35, 43, 289142)),
        ),
        migrations.AlterField(
            model_name='student',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 17, 35, 43, 287917)),
        ),
    ]
