# Generated by Django 4.1.7 on 2023-06-22 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': ' Classrooms',
                'db_table': 'Class Room',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter course name', max_length=100, verbose_name='Course name')),
                ('cost', models.CharField(blank=True, help_text='Enter cost', max_length=600, null=True, verbose_name='Cost')),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Enter Teacher Phone Number', max_length=15, null=True, unique=True, verbose_name='Teacher Phone Number')),
                ('added', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Employees',
                'db_table': 'Employee',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EmpType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'EmpType',
                'verbose_name_plural': 'EmpTypes',
                'db_table': 'EmpType',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Room name')),
            ],
            options={
                'verbose_name': ' Room ',
                'verbose_name_plural': ' Rooms ',
                'db_table': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Group name')),
                ('education', models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10, null=True)),
                ('day', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('waiting', 'Waiting')], max_length=10, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('finish', models.DateField(blank=True, null=True)),
                ('start_lesson', models.TimeField(blank=True, null=True)),
                ('finish_lesson', models.TimeField(blank=True, null=True)),
                ('course', models.ManyToManyField(related_name='groups', to='courses.course')),
                ('room', models.ManyToManyField(related_name='groups_rooms', to='courses.room')),
                ('teacher', models.ManyToManyField(related_name='teacher', to='courses.employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'Grouppa',
            },
        ),
        migrations.AddConstraint(
            model_name='emptype',
            constraint=models.UniqueConstraint(fields=('role',), name='unique_role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='course',
            field=models.ManyToManyField(to='courses.course'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.emptype'),
        ),
    ]
